name: 'BB Test Action'
description: 'Playground for actions'

inputs:
  enable-code-coverage:
    description: 'Boolean input to enable code coverage'
    required: false
    default: true

runs:
  using: 'composite'
  steps:
  - name: Run tests
    shell: bash
    run: |
      if [ "${{ inputs.enable-code-coverage }}" = "true" ]; then
        echo "1 "
        swift test --parallel --enable-code-coverage
      else
        echo "2 "
        swift test --parallel
      fi

branding:
  icon: 'server'
  color: 'green'