name: 'BB Test Action'
description: 'Playground for actions'

inputs:
  swift-format-version:
    description: 'Swift Format tag version number'
    required: false
    default: "510.1.0"

runs:
  using: 'composite'
  steps:
    - name: run script
      shell: bash
      run: |

        echo "${{github.action_path}}"
        echo "${GITHUB_ACTION_PATH}"

        # /home/runner/work/_actions/feather-actions/test-action/0.0.27/

        chmod -R oug+x ${{github.action_path}}/check-local-swift-dependencies.sh
        ${{github.action_path}}/check-local-swift-dependencies.sh

branding:
  icon: 'server'
  color: 'green'